version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    automerge: true
    automerge-options:
      security-updates: true
      new-version-when-dependency-changed: true
