env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
settings:
  react:
    version: detect
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
  - import
  - "@typescript-eslint"
rules:
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  react-hooks/exhaustive-deps: error
  react-hooks/rules-of-hooks: error
  no-unused-vars:
    - warn
    - args: none
  import/order:
    - error
    - groups:
        - "builtin"
        - "external"
        - "internal"
        - "parent"
        - "sibling"
        - "index"
      newlines-between: always
